CREATE TABLE if not exists Users (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(30) NOT NULL,
    password varchar(30),
    roleId int,
    FOREIGN KEY (roleId) REFERENCES Roles(id)
);