CREATE TABLE if not exists Resume
(
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(100),
    email      varchar(100),
    speciality varchar(100),
    about      varchar(100)
)