CREATE TABLE if not exists Bank_Account(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currencyId integer,
    userId integer,
    value integer,
    FOREIGN KEY (currencyId) REFERENCES Currency(id),
    FOREIGN KEY (userId) REFERENCES Users(id)
)