CREATE TABLE if not exists Indices(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pastYear integer,
    currentYear integer,
    value float8,
    currencyId integer,
    FOREIGN KEY (pastYear) REFERENCES Years(id),
    FOREIGN KEY (currentYear) REFERENCES Years(id),
    FOREIGN KEY (currencyId) REFERENCES Currency(id)
)