CREATE TABLE if not exists Indices(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     pastYear integer,
     nextYear integer,
     FOREIGN KEY (pastYear) REFERENCES Years(id),
     FOREIGN KEY (nextYear) REFERENCES Years(id)
)