INSERT INTO Currency (name, description)
values ('USD', 'United States Dollar'),
       ('EUR', 'Euro Member Countries'),
       ('RUB', 'Russia Ruble'),
       ('GBP', 'United Kingdom Pound'),
       ('CNY', 'China Yuan Renminbi'),
       ('IDR', 'Indonesia Rupiah'),
       ('BGN', 'Bulgaria Lev'),
       ('ILS', 'Israel Shekel'),
       ('DKK', 'Denmark Krone'),
       ('CAD', 'Canada Dollar'),
       ('JPY', 'Japan Yen'),
       ('HUF', 'Hungary Forint'),
       ('RON', 'Romania New Leu'),
       ('MYR', 'Malaysia Ringgit'),
       ('SEK', 'Sweden Krona'),
       ('SGD', 'Singapore Dollar'),
       ('HKD', 'Hong Kong Dollar'),
       ('AUD', 'Australia Dollar'),
       ('CHF', 'Switzerland Franc'),
       ('KRW', 'Korea (South) Won'),
       ('TRY', 'Turkey Lira'),
       ('HRK', 'Croatia Kuna'),
       ('NZD', 'New Zealand Dollar'),
       ('THB', 'Thailand Baht'),
       ('NOK', 'Norway Krone'),
       ('INR', 'India Rupee'),
       ('MXN', 'Mexico Peso'),
       ('CZK', 'Czech Republic Koruna'),
       ('BRL', 'Brazil Real'),
       ('PLN', 'Poland Zloty'),
       ('PHP', 'Philippines Peso'),
       ('ZAR', 'South Africa Rand');

