version: "3.9"
services:
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  currency_service:
    depends_on:
      - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile